#!/bin/bash
GREEN='\033[1;32m'
RED='\033[1;31m'
NC='\033[0m'
CYAN='\033[1;36m'

if test $# == 0; then
    echo "Enter input file"
    exit 1
fi

while [ "$1" ]; do
    echo -e "${GREEN}Test file: $1 ${NC}"
    for mode in ECB CBC CFB OFB CTR; do
        echo -e "${CYAN}Encrypt data..."

        filename=$(basename -- "${1}")
        ex="${filename##*.}"

        ./encrypt.py -m $mode -i meocon $1 ./test_space/$1.encrypt.${mode} 
        
        if test $? == 0; then
            echo "[*] Encrypt with $mode success"
        else
            echo -e "[*] ${RED}Encrypt with $mode failure${NC}"
        fi

        echo -e "${CYAN}Decrypt data...${NC}"
        ./decrypt.py -m $mode ./test_space/$1.encrypt.$mode ./test_space/$1.decrypt.$mode.$ex

        if test $? == 0; then
            echo "[*] Decrypt with $mode success"
        else
            echo -e "[*] ${RED}Decrypt with $mode failure${NC}"
        fi

    done
    shift 1
done


# echo -e "${CYAN}Compare checksum...${NC}"